call_expr.err.li 5,1: function `unknown_fn` is not defined
  > unknown_fn()
    ^^^^^^^^^^^^
call_expr.err.li 8,1: `v` is not function (`int`)
  > v()
    ^^^
call_expr.err.li 11,3: mismatched types: `int` (expected) and `string` (found)
  > f("a")
      ^^^
call_expr.err.li 12,1: expected 1 arguments, but got 0
  > f()
    ^^^
call_expr.err.li 13,1: expected 1 arguments, but got 2
  > f(0, 1)
    ^^^^^^^
