fn.err.li 1,14: `i` is duplicated
  > i
    ^
fn.err.li 2,10: unknown type `foo`
  > foo
    ^^^
fn.err.li 5,11: mismatched types: `string` (expected) and `int` (found)
  > i
    ^
fn.err.li 7,5: `g` is duplicated
  > g
    ^
fn.err.li 10,2: `v` is not function (`int`)
  > v()
    ^^^
fn.err.li 12,2: cannot call `int`
  > 0()
    ^^^
